### ISSUE TITLE
 Watch support?

### ISSUE THREAD

**Issue by NetOperatorWibby** [calleerlandsson/Tofu#10]
Hey Calle, I love Tofu and I tell people about it as much as I can (...just like people who eat tofu, lol). I recently purchased an  Watch and I was wondering if support for it was in the pipeline.

**Comment by calleerlandsson** [comment]
Hey @NetOperatorWibby, I'm happy you enjoy using Tofu and thanks for spreading the word about it! 😃 I haven't planned any time to work a watch extension but I'm definitely not opposed to one and if I get some time over I might work on it.
