### ISSUE TITLE
Touch ID + Share Extension

### ISSUE THREAD

**Issue by gh0stKid** [calleerlandsson/Tofu#12]
Hi, I was browsing for OTP apps in the App Store and had a difficult time choosing which one to use. I like Tofu mainly because it’s open-sourced. I’m trying out it for now and I do like to see a future update with Touch ID support to lock the app and a share sheet extension for autofill would be cool. Also, maybe a backup feature can be useful too?

**Comment by calleerlandsson** [comment]
Hey, @gh0stKid, those sounds like cool ideas! If you'd like to try your hands at implementing them, I'd be happy to answer your questions. If not, I can't really promise anything. If I build and ship something like this, I'll make sure to mention it in the release notes.
