### ISSUE TITLE
Ability to make a backup?

### ISSUE THREAD

**Issue by bluszcz** [calleerlandsson/Tofu#14]
Is there a way to backup the codes? This is a needed feature - in case of device loosing or device changing.

A good solution is implemented here: https://github.com/andOTP/andOTP

**Comment by calleerlandsson** [comment]
Hey @bluszcz!

The codes/passwords are stored in the keychain and should migrate to new devices when using encrypted device backups according to Apple’s documentation: https://developer.apple.com/documentation/security/ksecattraccessiblewhenunlocked
