### ISSUE TITLE
Read QR codes from Photos

### ISSUE THREAD

**Issue by TCB13** [calleerlandsson/Tofu#17]
Hello,

Thank you for building this App! One thing I miss is the ability to read the QR codes from images already stored in the Phone, or, the ability for other Apps to send images to Tofu.

Thank you.

**Comment by calleerlandsson** [comment]
Hey @TCB13, that sounds like a cool idea!

A pull request for this would be very welcome. I'll also consider working on this when I get some time to do so in the future.

**Comment by TCB13** [comment]
@calleerlandsson I'll check it when I get some time, however the last time I did something iOS was about 5 years now so ... no promisses.

**Comment by calleerlandsson** [comment]
This was added in #36.
