### ISSUE TITLE
Possible git sync?

### ISSUE THREAD

**Issue by robcohen** [calleerlandsson/Tofu#18]
I understand that tofu syncs with apple keychain. Is it feasible that tofu can backup to a custom git server? I run linux and doing backups isnt officially supported, so I try to use apps that sync to a git server I trust. Pass for iOS does this. Can tofu as well? Pss supports TOTP but passwords and totp in the same repo is a bad idea.

**Comment by calleerlandsson** [comment]
Hey @robcohen, thanks for the feedback!

Just like you wrote, Tofu stores account secrets in the iOS keychain. These secrets are then included in encrypted device backups made with iTunes or via iCloud.

In the future, I might consider working on an alternative backup option but I'm worried that using Git for this might make the feature hard to use for people who have no prior experience with version control systems.
