### ISSUE TITLE
Importing data from Google Authenticator

### ISSUE THREAD

**Issue by ghost** [calleerlandsson/Tofu#24]
It'd make transferring easier so I do not have to have a lock on all of my accounts for 30 days because I changed the auth app

**Comment by calleerlandsson** [comment]
Hi @Jeremia-h, thanks for the feedback!

I agree that such an import would be really convenient. I'm not sure how it would be implemented, though!

I think the Google Authenticator app stores secrets in the keychain and there's no way for Tofu to access these. Unless there's an export function in the Google Authenticator app, which to my knowledge there isn't, I don't think there's a way to get the data.

Do you have any ideas for how this could be implemented?

**Comment by Jeremia-h** [comment]
I'm not sure. Authentication keys are backed up in iCloud on iOS and I'm sure something similar happens on Android. Maybe there is a way to access that data manually?

**Comment by calleerlandsson** [comment]
I don't think there is. Apps do not have direct access to iCloud backups or the keychain items of other apps.
