### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by ghost** [calleerlandsson/Tofu#25]
Would you consider implementing a dark theme for the app? (sort of goes against the feel of "Tofu" but it's still a nice-to-have)

**Comment by calleerlandsson** [comment]
I definitely would like Tofu to support the dark mode in iOS 13. If someone wants to work on that, I'd really appreciate it.

**Comment by calleerlandsson** [comment]
Support for dark mode was added in 4cc7bbd41a5dae320518b4441d60c66b6bb04bed. I'm putting out a TestFlight build of this today and will hopefully release it on the AppStore in a week or two.
