### ISSUE TITLE
Suggestions for new site icons

### ISSUE THREAD

**Issue by RazziaDK** [calleerlandsson/Tofu#31]
I would like to suggest a few more logos to be added to the app.

I'm not sure how I can submit them myself, but I found logos for the following sites. On the sites there is SVG, PDF, JPG and PNG available.
NiceHash - https://www.nicehash.com/media
Basecamp - https://basecamp.com/about/press
Time4VPS - https://www.time4vps.com/wp-content/uploads/2017/03/logo.svg

**Comment by frozenshadow** [comment]
I'll take a look at it later this week. The first link is dead btw. :wink:

**Comment by RazziaDK** [comment]
> 
> 
> I'll take a look at it later this week. The first link is dead btw. 😉

Thanks!
The first link works for me, but I can see they have a logo collection on Dropbox as well: https://www.dropbox.com/s/qwjm1rya75dog0h/nh_logos.zip?dl=0

**Comment by frozenshadow** [comment]
You're right, the link works. My DNS provider just didn't pick it up ¯\_(ツ)_/¯

Anyway, I added the icons. The Time4VPS was a bit tricky due to the horizontal nature of their logo, so I just recreated the favicon logo.
Hope you like them and please let me know what you think!

**Comment by RazziaDK** [comment]
Nice solution to the Time4VPS logo!
The others icons looks good as well.

How does the app recognize which icon it should use?
I have added 2FA to my Synology NAS, and in the app it shows up as "<Username>@<Custom-NAS-name>". Would it be possible to add a Synology icon without a common NAS name?

**Comment by frozenshadow** [comment]
Glad to hear you like the icons!

The icons are based on their issuer and their names are defined in this file: [Tofu/AccountCell.swift](https://github.com/calleerlandsson/Tofu/blob/master/Tofu/AccountCell.swift#L22)
So for example: you setup 2FA for GitHub, the qr code you scan contains the issuer name 'GitHub' and thus (in this case) equals to [line 45](https://github.com/calleerlandsson/Tofu/blob/master/Tofu/AccountCell.swift#L45).

Fun fact: if you want a different icon or the related icon does not appear, just tap the edit button in the app and edit the 'Issuer' field of the desired entry to match one of the definitions listed in the file above :wink:

**Comment by RazziaDK** [comment]
Thanks again!
Do you need issuing information about the three new logos?
Basecamp = "Basecamp's+Launchpad"
NiceHash = "NiceHash - New platform"
Time4VPS is empty. :-(

**Comment by frozenshadow** [comment]
I've edited the issuer names. Should be good to go now.

**Comment by RazziaDK** [comment]
Thanks!
