### ISSUE TITLE
Backups work or not?

### ISSUE THREAD

**Issue by nistan123** [calleerlandsson/Tofu#33]
I’m on: macOS Catalina (10.15.2), intending to back up Tofu (latest AppStore release) on an iPad (13.3).

Just need to know before I do some mandatory iPad maintenance and restore my device with a clean install, can I expect to lose all my Tofu data when restoring it from an encrypted icloud/hdd backup or not?

 There’s not exactly a whiteboard here where it lists the recommended ’do’s and don’ts’, to summarily recommend novice users on what to be mindful of in the latest build. Just a side note: might be good to have an issue like this pinned to the top, maybe? There are just various reports of people losing their Tofu data when restoring iCloud/hdd encrypted backup. Not very reassuring. 

So should I refrain from it and use another app, or not?
Don’t mind helping out and testing too. But first I need to secure my accounts.

**Comment by calleerlandsson** [comment]
Hey @nistan123, as far as I know, we're doing everything we can to have iOS include Tofu's accounts in it's encrypted backups. Despite this, we have had instances where the accounts haven't been restored from iCloud backups. Unfortunately, I can't give you any more information or guarantees than that.

If you would like to help debug this issue by attempting to restore your device from a fresh encrypted iTunes backup I would really appreciate it! If you do, please report back in #16.

> But first I need to secure my accounts.

Regardless of backups working properly or not, I highly recommend downloading and/or printing the recovery codes provided by issuers.

**Comment by nistan123** [comment]
> If you would like to help debug this issue by attempting to restore your device from a fresh encrypted iTunes backup I would really appreciate it! If you do, please report back in #16.

Will do if I get a chance to, as soon as possible.

**Comment by nistan123** [comment]
> Regardless of backups working properly or not, I highly recommend downloading and/or printing the recovery codes provided by issuers.

Good point. Thanks.
