### ISSUE TITLE
Autofill OTP passwords

### ISSUE THREAD

**Issue by ghost** [calleerlandsson/Tofu#34]
May I suggest some features?

1) 

2) A small quality of life upgrade would be that to merely double tap a token in the app should directly copy the code to the clipboard, rather than having to tap and then press Copy. I think most other Auth apps I’ve tried has this design (though trivial change).

3) An incredibly convenient option would be for the Tofu app to automatically send the current code for the relevant token to the clipboard, similar to how when signing in to a website with a text message verification code it appears automatically in the clipboard (without having to leave the Safari app). Would this be feasible?

**Comment by nistan123** [comment]
Silly me, there's a search function already... Calling myself stupid so nobody else needs to. Done. :)

**Comment by calleerlandsson** [comment]
Hey @nistan123, thanks for the feedback.

> merely double tap a token in the app should directly copy the code to the clipboard

Right now, when the contextual menu disappears after tapping the Copy item, I think people have the expectation that the code was copied to the clipboard. If we didn't display a contextual menu and instead copied codes on double tap, I'm not sure how we could create this expectation or otherwise provide feedback in a way that's in line with the rest of the system.

> [...] the Tofu app to automatically send the current code for the relevant token to the clipboard [...] Would this be feasible?

Unfortunately, I don't think that's possible with the currently available APIs.

**Comment by dietofworms** [comment]
To extend upon OP's request regarding copying the code automatically. Can we take a look at Google's Authenticator application for inspiration? There, you can simply tap a code and it will automatically copy it to your clipboard. I think this feature would be really good to implement in Tofu.

**Comment by nistan123** [comment]
Just to adding an example you may want to have a look at re. suggested feature #3. 
The iOS app 1Password offers this exact feature. After installing the app, go Settings > Passwords and Accounts > Autofill Passwords, and then you may add the 1Password app.
Maybe have a closer look at how they do it?

**Comment by sekizuri** [comment]
> The iOS app 1Password offers this exact feature. After installing the app, go Settings > Passwords and Accounts > Autofill Passwords, and then you may add the 1Password app.

Can update that this feature has not worked at all in 1Password. So perhaps it is impossible to do this currently...

**Comment by calleerlandsson** [comment]
Regarding one-tap copy: I don’t think the way Google Authenticator provides feedback that it copied the code to the clipboard fits in well with the rest of system. If you have suggestions for how to do this better, I’d love to hear them.

Regarding 1Password and autofill: If I have understood things correctly, the autofill api lets apps pre-register entries that can be auto filled. I don’t see how this would work with short lived one time passwords.

**Comment by sekizuri** [comment]
> Regarding 1Password and autofill: If I have understood things correctly, the autofill api lets apps pre-register entries that can be auto filled. I don’t see how this would work with short lived one time passwords.

![371BDDD4-CC4E-4F9F-83B6-9A288C5AC117](https://user-images.githubusercontent.com/58093076/71518790-d5897080-28b4-11ea-9ddc-c90796a2a931.png)

Although I haven’t gottne it to work myself, clearly it is supposed to, if you refer to the image attached.

Imagine how smooth the user experience would be to simply log in to websites and never having to even open Tofu, but just stay in Safari? 
It could set your app apart from the rest if you implemented this (and it actually works).

**Comment by calleerlandsson** [comment]
> Imagine how smooth the user experience would be to simply log in to websites and never having to even open Tofu, but just stay in Safari?

I agree that it sounds great! I still don't see how it would work, though.

The way I interpret this 1Password feature is that after autofilling your username/email and password, 1Password will copy the OTP to your clipboard for you to then paste into the OTP field. This seems reliant on getting a callback from the autofill system, and I'm not sure how Tofu would handle that?

**Comment by sekizuri** [comment]
> This seems reliant on getting a callback from the autofill system, and I'm not sure how Tofu would handle that?

Sorry to say I know nothing about programming/coding, I’m only a lowly consumer. But I found a similar open source project on github which claims to be using auto-fill 2FA [https://github.com/FoxAuth/FoxAuth](here). Perhaps have a look at their code? Although this is not  for iOS but Mozilla.

**Comment by ThinkChaos** [comment]
> Regarding 1Password and autofill: If I have understood things correctly, the autofill api lets apps pre-register entries that can be auto filled. I don’t see how this would work with short lived one time passwords.

The API actually launches an app extension that can do more than just register entries. For instance KeepassTouch, a password manager based on MiniKeepass, has an autofill extension that asks the user to unlock the database and then can fetch relevant username/password combos.

What I'm not sure about is if iOS would allow the autofill extension to run for non username/password fields. I think 2FA code inputs generally don't match username nor password detection.

**Comment by sekizuri** [comment]
Something else which might be of interest is how Strongbox for iOS can (I assume) copy relevant TOTPs directly: 
![A6D82C71-7222-49AF-8380-9C0B664FB167](https://user-images.githubusercontent.com/58093076/71524833-8a308b80-28cf-11ea-97c0-d65e38e68168.png)

**Comment by bre7** [comment]
OTP autofill on iOS only works for SMS login flows. https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_a_text_input_view

1Password for example, autofills user/password and sends the OTP code to the clipboard.

**Comment by calleerlandsson** [comment]
I don't think this is technically possible right now. Let's re-open this if this changes!

**Comment by mietzen** [comment]
I found this old pull request: https://github.com/mattrubin/Authenticator/pull/234
Perhaps this would be a possible workaround, we still have to make multiple clicks/taps but we don't need to switch the app / lose focus.
