### ISSUE TITLE
Icon request - Hey.com

### ISSUE THREAD

**Issue by RazziaDK** [calleerlandsson/Tofu#42]
I would like to see a icon added for Hey.com - a new email service.
I not sure how to do it myself, but hopefully some helpful soul can assist.

I found their logo as SVG here:
https://hey.com/assets/general/hand-peace-8b40e9460a1ae55d834563cc1cdc8b4aef606e58241d244f0468cb59442911a4.svg

In Tofu the service is listed as: "HEY (myEmail@hey.com)"

Thanks in advance!

**Comment by frozenshadow** [comment]
Thanks for the request!
I will get to it this weekend.

**Comment by frozenshadow** [comment]
I've made a PR including this issuer. I tried to replicate the 'HEY Email' app icon.
Please, let me know what you think.

**Comment by RazziaDK** [comment]
> I've made a PR including this issuer. I tried to replicate the 'HEY Email' app icon.
> Please, let me know what you think.

Looks good!
