### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by lg2518** [calleerlandsson/Tofu#46]
Is it possible to get icons for Reddit, Snapchat and Instagram? Not sure how to do it myself, happy to do so though if someone can point me in the right direction.

Love the app!

**Comment by frozenshadow** [comment]
Thanks for the suggestion!
I'll try to create some this weekend.

**Comment by frozenshadow** [comment]
I've made a PR with the requested icons.
Please, let me know what you think.
