### ISSUE TITLE
Some additional icons

### ISSUE THREAD

**Issue by frozenshadow** [calleerlandsson/Tofu#5]
First of all, I love the app! It is simple, fast and best of all open-source.
I do however have a request for some icons:
- WordPress
- Electronic Arts
- Ubisoft

Can you add these?
Thanks in advance, and keep up the good work :)

**Comment by calleerlandsson** [comment]
Hey @frozenshadow, I'm happy you're enjoying Tofu!

I'm currently working on the next release of the app. I can't say when it will be available to download but I'll do my best to include these icons in it!

**Comment by frozenshadow** [comment]
Great! Looking forward to the next release.

Thank you for the quick response.
