### ISSUE TITLE
Please add following icons

### ISSUE THREAD

**Issue by Widkidone** [calleerlandsson/Tofu#53]
Please add Privacy.com, Anonaddy, Surfshark and  Intuit (TurboTax), and Tresorit.

**Comment by frozenshadow** [comment]
Hi Widkidone, sorry for the delayed response and thank you for your request!
Life is a bit hectic at the moment, but I will try to make some icons soon.
I'll let you know when they are ready.

**Comment by frozenshadow** [comment]
The Privacy.com and Tresorit icons where already added as can be seen here:
https://github.com/calleerlandsson/Tofu/blob/6622de6e5f81f33c370104606a5fd25ffb0aea15/Tofu/AccountCell.swift#L88
https://github.com/calleerlandsson/Tofu/blob/6622de6e5f81f33c370104606a5fd25ffb0aea15/Tofu/AccountCell.swift#L98
So I've only made icons for AnonAddy, Surfshark and TurboTax.
Please, let me know what you think of them!

**Comment by calleerlandsson** [comment]
Added in #56
