### ISSUE TITLE
Add option to change color of "icons" 

### ISSUE THREAD

**Issue by tycm** [calleerlandsson/Tofu#59]
It'd be nice to be able to change the color of the letter and background for items without an icon.

**Comment by calleerlandsson** [comment]
Hi @tycm, thanks for the suggestion! My goal is to one day support user provided issuer icons. Maybe that can serve the same purpose as custom colored letters and backgrounds?

**Comment by tycm** [comment]
That would definitely be better, I was just wondering if it would be easy to implement and it would match how you're able to change the background color for contacts in iOS 

![image](https://user-images.githubusercontent.com/44624889/105390939-988ecb00-5be7-11eb-8d70-6059e0dd4d45.png)

**Comment by calleerlandsson** [comment]
That's an interesting idea, and I see how it could be useful! Let's do user provided icons first, then we can see how this could fit in.
