### ISSUE TITLE
Copy-on-click

### ISSUE THREAD

**Issue by akerl** [calleerlandsson/Tofu#7]
Given that there's no action when you click on a row, it would be cool if clicking automatically copied the token (this is what the Google Auth app does).

That way, I'd not have to press-and-hold and then select Copy

**Comment by calleerlandsson** [comment]
I think this is a good idea. I did try this at one point but it interfered with the "advance counter" button for counter based tokens. I think we might be able to make it a bit simpler by allowing one to tap to bring up the context-menu instead of tap-and-hold.
