### ISSUE TITLE
Register URL handler

### ISSUE THREAD

**Issue by nielslaukens** [calleerlandsson/Tofu#8]
It would be nice if TOFU would register itself as a URL handler for the otpauth:// scheme, just like the Google Authenticator app does. This would allow you to click on a otpauth:// link in e.g. a text message, and have the app automatically open and add the token (maybe after a confirmation).

I believe most of the logic is already implemented for decoding a QR-code, only the registration with iOS for otpauth:// URLs is missing.

**Comment by calleerlandsson** [comment]
Hey @nielslaukens, that sounds like a cool idea! Do you have an example of an issuer that supply this kind of links?

**Comment by nielslaukens** [comment]
:-) My employer...
The system automatically generates OTP configuration, and sends it via a text message to the users. Typically, the text will be received on the same smartphone that will be used for OTP-generation. Copy-pasting works, but is cumbersome.
If the Google Authenticator app is installed, the user can simply click on the link and the OTP-config is added to the app. It would be nice if TOFU would do the same.

**Comment by calleerlandsson** [comment]
Ah, I see! I agree that it would be a nice feature. Thanks for proposing it, @nielslaukens!

If someone wants to work on this, I'd be happy to answer questions and review PRs. If not, I'll get to it when I can find the time.

**Comment by TCB13** [comment]
+1 on this!

**Comment by ThinkChaos** [comment]
For anyone looking into this, [here](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) is a reference on the URL scheme.
